// Local-only integration checks. Never point this at production.
import assert from 'node:assert/strict';
import { deflateSync } from 'node:zlib';
const base='http://127.0.0.1:5173',cookie='__sites_local_auth=1';
const get=(path,auth=false)=>fetch(base+path,{headers:auth?{cookie}:{},redirect:'manual'});
async function post(action,values={},auth=true,origin=base){const body=new FormData();body.set('action',action);for(const [key,value]of Object.entries(values))body.set(key,value);const response=await fetch(base+'/api/actions',{method:'POST',headers:{Origin:origin,Accept:'application/json',...(auth?{cookie}:{})},body});const payload=await response.text();let result;try{result=JSON.parse(payload);}catch{result={error:payload};}return {status:response.status,...result};}
const fields=html=>Object.fromEntries([...html.matchAll(/<input[^>]*name="(id|version)"[^>]*value="([^"]*)"/g)].map(m=>[m[1],m[2]]));
let checks=0;const check=(condition,message)=>{assert.ok(condition,message);checks++;console.log('PASS',message);};
check((await get('/api/health')).status===200,'database, object storage and admin configuration ready locally');
check((await get('/account')).status===307 || (await get('/account')).status===302,'anonymous account requires sign-in');
check((await post('profile.save',{name:'Test'},false)).status===401,'anonymous writes rejected');
check((await post('profile.save',{name:'Test'},true,'https://other.example')).status===403,'cross-site writes rejected');
check((await get('/account',true)).status===200,'ChatGPT local identity creates persistent profile');
check((await post('profile.save',{name:'Local QA Owner'})).status===200,'profile changes persist');
let r=await post('business.save',{name:'Local QA Studio',category:'Art & Creators',location:'London',summary:'A local-only test business for verification.',description:'This is a local-only Christian business fixture used to verify the Sites backend.',website:'https://example.com',faith:'yes'});
if(r.status!==200){const current=fields(await (await get('/account/business',true)).text());r=await post('business.save',{...current,name:'Local QA Studio',category:'Art & Creators',location:'London',summary:'A local-only test business for verification.',description:'This is a local-only Christian business fixture used to verify the Sites backend.',website:'https://example.com',faith:'yes'});}
check(r.status===200,'business application saved');
check(!(await (await get('/businesses')).text()).includes('Local QA Studio'),'pending business is not public');
r=await post('product.save',{name:'Local QA Print',description:'A local-only product used to verify permissions and image publication.',category:'Art & Prints',price:'19.99',stock:'3',delivery_info:'Local test only. No real delivery or purchases.'});
check(r.status===200,'seller creates product draft');
const productPath=r.redirect.split('?')[0],productId=productPath.split('/').pop();
let product=fields(await (await get(productPath,true)).text());
check((await get('/products/'+productId)).status===404,'draft product is private');
check((await post('product.status',{...product,status:'published'})).status===400,'publication blocked without approved business/photo');
check((await post('product.save',{...product,name:'Bad',description:'A valid length description for an invalid price.',category:'Art & Prints',price:'-2',stock:'1',delivery_info:'This is just a test delivery.'})).status===400,'invalid prices rejected on server');
check((await post('photo.upload',{...product,photo:new File(['not an image'],'fake.png',{type:'image/png'})})).status===400,'disguised image rejected');
const crc=data=>{let c=0xffffffff;for(const byte of data){c^=byte;for(let i=0;i<8;i++)c=(c>>>1)^((c&1)?0xedb88320:0);}return (c^0xffffffff)>>>0;};
const chunk=(type,data)=>{const b=Buffer.alloc(data.length+12);b.writeUInt32BE(data.length);b.write(type,4);data.copy(b,8);b.writeUInt32BE(crc(b.subarray(4,-4)),b.length-4);return b;};
const header=Buffer.alloc(13);header.writeUInt32BE(1);header.writeUInt32BE(1,4);header[8]=8;header[9]=6;
const png=Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),chunk('IHDR',header),chunk('tEXt',Buffer.from('Private metadata should be stripped')),chunk('IDAT',deflateSync(Buffer.from([0,100,130,160,255]))),chunk('IEND',Buffer.alloc(0))]);
r=await post('photo.upload',{...product,photo:new File([png],'test.png',{type:'image/png'})});check(r.status===200,'validated PNG stored in object storage');
const editor=await (await get(productPath,true)).text(),photo=editor.match(/\/api\/photos\/([a-f0-9-]+)/)?.[1];check(!!photo,'photo appears in seller editor');
check((await get('/api/photos/'+photo)).status===404,'draft photo is private');
const photoBytes=Buffer.from(await (await get('/api/photos/'+photo,true)).arrayBuffer());check(!photoBytes.includes(Buffer.from('Private metadata')),'photo metadata stripped server-side');
const business=fields(await (await get('/account/business',true)).text());
r=await post('business.review',{...business,status:'approved',review_note:'Approved in local QA only.'});check(r.status===200,'admin approves real application record');
check((await (await get('/businesses')).text()).includes('Local QA Studio'),'approved business becomes public');
product=fields(await (await get(productPath,true)).text());r=await post('product.status',{...product,status:'published'});check(r.status===200,'approved seller publishes product');
check((await get('/products/'+productId)).status===200,'published product is discoverable');
check((await get('/api/photos/'+photo)).status===200,'published photo becomes public');
check((await post('product.status',{...product,status:'draft'})).status===400,'stale update cannot overwrite newer version');
product=fields(await (await get(productPath,true)).text());r=await post('product.moderate',{...product,moderation_status:'hidden'});check(r.status===200,'admin hides product');
check((await get('/products/'+productId)).status===404 && (await get('/api/photos/'+photo)).status===404,'moderated product and photo become private together');
r=await post('event.save',{name:'Local QA Gathering',organiser:'Local test organiser',location:'London',schedule:'Local QA fixture, not a real event',description:'A local-only event fixture to verify draft, publication and archive permissions.',website:'https://example.com'});check(r.status===200,'admin creates event draft');
const eventPath=r.redirect.split('?')[0],eventId=eventPath.split('/').pop();let event=fields(await (await get(eventPath,true)).text());
check((await get('/events/'+eventId)).status===404,'event draft stays private');
r=await post('event.status',{...event,status:'published'});check(r.status===200 && (await get('/events/'+eventId)).status===200,'event publication works');
event=fields(await (await get(eventPath,true)).text());r=await post('event.status',{...event,status:'archived'});check(r.status===200 && (await get('/events/'+eventId)).status===404,'event archive hides public detail');
check((await (await get('/notifications',true)).text()).includes('Approved in local QA only'),'application notification persisted');
console.log(`${checks} local integration checks passed. Test records exist only in local .wrangler state.`);
