import Link from "@/components/site-link";
import { admin } from "@/lib/admin";
import { all, search, like, pageNumber, type Business } from "@/lib/data";
import { AdminNav, Saved, Empty } from "@/components/page-ui";
import { ActionForm } from "@/components/action-form";
import { HiddenRecord } from "@/components/forms";
export const dynamic="force-dynamic";
export default async function AdminPage({searchParams}:{searchParams:Promise<{saved?:string;q?:string;page?:string}>}){const query=await searchParams;return <Content query={query}/>;}
async function Content({query}:{query:{saved?:string;q?:string;page?:string}}){await admin();const q=search(query.q),page=pageNumber(query.page),businesses=await all<Business>("SELECT * FROM hh_businesses WHERE name LIKE ? ESCAPE '\\' ORDER BY CASE status WHEN 'pending' THEN 0 ELSE 1 END,updated_at DESC LIMIT 21 OFFSET ?",like(q),(page-1)*20);return <><AdminNav/><Saved value={query.saved}/><h1 className="page-title">Welcome the next great brand.</h1><p>Review each business and its website before approving. Suspended businesses and their products are hidden.</p><form className="search-bar event-search"><div className="field"><label htmlFor="q">Find a business</label><input id="q" name="q" defaultValue={q} maxLength={80}/></div><button className="button button-primary">Search</button></form><div className="review-list top-space">{businesses.slice(0,20).map(b=><article className="card" key={b.id}><div className="split-heading"><h2>{b.name}</h2><span className="status-pill">{b.status}</span></div><p>{b.category} · {b.location}</p><p>{b.summary}</p><p className="preserve-lines">{b.description}</p>{b.website&&<p><a className="text-link" href={b.website} target="_blank" rel="noopener noreferrer">Review business website ↗</a></p>}<ActionForm action="business.review"><HiddenRecord record={b}/><div className="field"><label htmlFor={`decision-${b.id}`}>Decision</label><select id={`decision-${b.id}`} name="status" defaultValue="approved"><option value="approved">Approve</option><option value="rejected">Request changes / reject</option><option value="suspended">Suspend public listing</option></select></div><div className="field"><label htmlFor={`note-${b.id}`}>Message to the owner</label><textarea id={`note-${b.id}`} name="review_note" maxLength={1000} required defaultValue={b.review_note}/></div><button className="button button-primary">Save review decision</button></ActionForm></article>)}</div>{!businesses.length&&<Empty title="No applications to review."><p>New business applications will appear here.</p></Empty>}{(page>1||businesses.length>20)&&<nav className="pagination">{page>1?<Link href={`/admin?q=${encodeURIComponent(q)}&page=${page-1}`}>← Previous</Link>:<span/>}{businesses.length>20&&<Link href={`/admin?q=${encodeURIComponent(q)}&page=${page+1}`}>Next →</Link>}</nav>}</>;}
