import Link from "next/link";
import { notFound } from "next/navigation";
import { requireUser } from "@/lib/auth/require-user";
import { isUuid } from "@/lib/businesses";
import { money } from "@/lib/marketplace";
import { Notices } from "@/components/notices";
import { SubmitButton } from "@/components/submit-button";
import { requestRefund } from "../actions";
export default async function NewRefund({searchParams}:{searchParams:Promise<{item?:string;error?:string}>}){const params=await searchParams;if(!isUuid(params.item))notFound();const {supabase,user}=await requireUser();const {data:item,error}=await supabase.from("order_items").select("*").eq("id",params.item).maybeSingle();if(error)throw new Error("Order item unavailable");if(!item)notFound();const {data:order}=await supabase.from("orders").select("id,status").eq("id",item.order_id).eq("customer_id",user.id).maybeSingle();if(!order||!["paid","partially_refunded"].includes(order.status))notFound();return <section className="content-narrow"><Link className="text-link" href={`/orders/${order.id}`}>← Your order</Link><div className="section-heading"><p className="eyebrow">Let’s understand what happened</p><h1 className="page-title">Request a refund.</h1><p>{item.product_name} · Item total {money(item.total_pence)}</p></div><Notices error={params.error}/><form action={requestRefund} className="card form"><input type="hidden" name="item" value={item.id}/><div className="field"><label htmlFor="reason">What is the issue?</label><select id="reason" name="reason" required><option value="not_received">Item not received</option><option value="damaged">Damaged or faulty</option><option value="not_as_described">Not as described</option><option value="other">Something else</option></select></div><div className="field"><label htmlFor="explanation">Tell us what happened</label><textarea id="explanation" name="explanation" minLength={20} maxLength={5000} rows={6} required/></div><div className="field"><label htmlFor="contacted_seller">Have you contacted the seller?</label><select name="contacted_seller" id="contacted_seller" required><option value="no">Not yet</option><option value="yes">Yes</option></select></div><div className="field"><label htmlFor="desired_resolution">What outcome are you asking for?</label><textarea id="desired_resolution" name="desired_resolution" rows={3} minLength={5} maxLength={1000} required/></div><div className="field"><label htmlFor="amount">Refund requested (£)</label><input id="amount" name="amount" inputMode="decimal" defaultValue={(item.total_pence/100).toFixed(2)} maxLength={10} required/></div><p className="muted-small">The seller can respond and HolyHub will make the decision. You can add photos or screenshots after submitting. Do not include bank details, card numbers or unnecessary personal information.</p><SubmitButton pendingText="Submitting…">Send refund request →</SubmitButton></form></section>;}
