import Link from "next/link";
import { notFound } from "next/navigation";
import { requireUser } from "@/lib/auth/require-user";
import { isUuid } from "@/lib/businesses";
import { money,statusLabel,type RefundCase } from "@/lib/marketplace";
import { Notices } from "@/components/notices";
import { SubmitButton } from "@/components/submit-button";
import { respondRefund,decideRefund,appealRefund } from "../actions";
import { uploadRefundEvidence } from "@/app/uploads/actions";
export default async function RefundPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{error?:string;message?:string}>}){
 const {id}=await params;if(!isUuid(id))notFound();const {supabase,user}=await requireUser(`/refunds/${id}`);const {data,error}=await supabase.from("refund_cases").select("*").eq("id",id).maybeSingle();if(error)throw new Error("Refund case unavailable");if(!data)notFound();const r=data as RefundCase;
 const [{data:roles},{data:business},{data:messages,error:messageError},{data:evidence,error:evidenceError}]=await Promise.all([supabase.from("user_roles").select("role").eq("user_id",user.id),supabase.from("businesses").select("owner_id,name").eq("id",r.business_id).maybeSingle(),supabase.from("refund_messages").select("*").eq("refund_id",id).order("created_at"),supabase.from("refund_evidence").select("*").eq("refund_id",id).order("created_at")]);if(messageError||evidenceError)throw new Error("Case history unavailable");const admin=roles?.some(x=>x.role==="admin"),seller=business?.owner_id===user.id,customer=r.customer_id===user.id;const canAppeal=(seller||customer)&&["approved","partially_approved","rejected"].includes(r.status)&&r.appeal_deadline&&new Date(r.appeal_deadline)>new Date()&&r.appeal_limit!==null&&r.appeal_count<r.appeal_limit&&r.payment_status!=="paid";
 return <section className="content-narrow"><Link className="text-link" href={admin?"/admin/refunds":seller?"/seller/orders":"/orders"}>← Back</Link><div className="section-heading"><p className="eyebrow">Refund case {id.slice(0,8).toUpperCase()}</p><h1 className="page-title">A fair hearing, on both sides.</h1><span className="status-pill">{statusLabel(r.status)}</span></div><Notices {...await searchParams}/><section className="card"><h2>Customer request</h2><p><strong>{money(r.requested_pence)} requested</strong> · {statusLabel(r.reason)}</p><p className="preserve-lines">{r.explanation}</p><h3>Requested outcome</h3><p className="preserve-lines">{r.desired_resolution}</p><p className="muted-small">Seller contacted before the request: {r.contacted_seller?"Yes":"No"}</p></section><section className="card top-space"><h2>Evidence</h2><p>Photos and screenshots are private to the people involved and HolyHub reviewers. Avoid unnecessary personal information.</p><div className="evidence-list">{evidence?.map((e,index)=><a key={e.id} className="button button-quiet" href={`/api/evidence/${e.id}`} target="_blank" rel="noopener noreferrer">Evidence {index+1} · {e.author_id===r.customer_id?"Customer":"Seller / reviewer"} ↗</a>)}</div>{r.status!=="closed"&&(evidence?.filter(e=>e.author_id===user.id).length??0)<5&&<form action={uploadRefundEvidence} className="form top-space"><input type="hidden" name="id" value={id}/><div className="field"><label htmlFor="image">Add evidence (JPG, PNG or WebP; up to 5 MB)</label><input type="file" id="image" name="image" accept="image/jpeg,image/png,image/webp" required/></div><SubmitButton pendingText="Uploading…">Upload evidence</SubmitButton></form>}</section>
 {seller&&["requested","awaiting_seller_response"].includes(r.status)&&<form action={respondRefund} className="card form top-space"><h2>Your response</h2><input type="hidden" name="id" value={id}/><div className="field"><label htmlFor="response">Explain your position and evidence</label><textarea name="response" id="response" rows={6} minLength={20} maxLength={5000} required/></div><SubmitButton>Submit response for review</SubmitButton></form>}
 <section className="card top-space"><h2>Case history</h2>{!messages?.length&&<p>The seller has been notified in their HolyHub account.</p>}{messages?.map(m=><article className="case-message" key={m.id}><strong>{statusLabel(m.kind)}</strong><p className="preserve-lines">{m.body}</p><time className="muted-small">{new Date(m.created_at).toLocaleString("en-GB",{timeZone:"UTC"})} UTC</time></article>)}</section>
 {admin&&["requested","awaiting_seller_response","under_review","appealed"].includes(r.status)&&<form action={decideRefund} className="card form top-space"><h2>HolyHub decision</h2><p>Review both sides and all evidence. Explain your reasoning, including any missing seller response. This records a human decision; it does not send a refund.</p><input type="hidden" name="id" value={id}/><div className="field"><label htmlFor="decision">Decision</label><select name="decision" id="decision"><option value="approved">Approve requested amount</option><option value="partially_approved">Partially approve</option><option value="rejected">Reject</option></select></div><div className="field"><label htmlFor="amount">Approved amount (£); use 0 for rejection</label><input name="amount" id="amount" inputMode="decimal" defaultValue={(r.requested_pence/100).toFixed(2)} required/></div><div className="field"><label htmlFor="note">Reasons for the decision (shared with both sides)</label><textarea name="note" id="note" rows={5} minLength={20} maxLength={5000} required/></div><SubmitButton>Record decision</SubmitButton></form>}
 {r.approved_pence>0&&<p className="notice notice-info top-space">Approved: {money(r.approved_pence)}. Refund payment status: {statusLabel(r.payment_status)}. An approved decision is not a confirmation that money has been returned.</p>}
 {canAppeal&&<form action={appealRefund} className="card form top-space"><h2>Ask HolyHub to review the decision</h2><input type="hidden" name="id" value={id}/><div className="field"><label htmlFor="appeal">Explain your appeal and any new evidence</label><textarea name="explanation" id="appeal" minLength={20} maxLength={5000} rows={5} required/></div><SubmitButton>Submit appeal</SubmitButton></form>}
 {!canAppeal&&["approved","partially_approved","rejected"].includes(r.status)&&<p className="muted-small">No appeal is currently available in the app. <a className="text-link" href="mailto:Official.holyhub@gmail.com">Contact HolyHub</a> if you need help understanding your options.</p>}</section>;
}
