import Image from "next/image";
import Link from "@/components/site-link";
import { notFound } from "next/navigation";
import { member, all, one, productSelect, type Product } from "@/lib/data";
import { AccountNav, Saved } from "@/components/page-ui";
import { ProductForm, HiddenRecord } from "@/components/forms";
import { ActionForm } from "@/components/action-form";
export const dynamic="force-dynamic";
export default async function EditProduct({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{saved?:string}>}){const {id}=await params,query=await searchParams;return <Content id={id} saved={query.saved}/>;}
async function Content({id,saved}:{id:string;saved?:string}){const user=await member(`/seller/products/${id}`),product=await one<Product>(productSelect+" WHERE p.id=? AND b.owner_id=?",id,user.id);if(!product)notFound();const photos=await all<{id:string}>("SELECT id FROM hh_photos WHERE product_id=? ORDER BY created_at,id LIMIT 5",id);return <><AccountNav/><Saved value={saved}/><div className="split-heading"><h1 className="page-title">{product.name}</h1><span className="status-pill">{product.status} · {product.moderation_status}</span></div><div className="product-detail-grid"><section className="card"><ProductForm product={product}/></section><div><section className="card"><h2>Show what makes it special.</h2><p>Up to five photos. The first is your cover image. To change photos, save the product as a draft.</p><div className="photo-manager">{photos.map(photo=><div key={photo.id}><Image src={`/api/photos/${photo.id}`} unoptimized width={120} height={120} alt={product.name}/>{product.status==="draft"&&<ActionForm action="photo.remove"><HiddenRecord record={product}/><input type="hidden" name="photo_id" value={photo.id}/><button className="button button-quiet">Remove photo</button></ActionForm>}</div>)}</div>{product.status==="draft"&&photos.length<5&&<ActionForm action="photo.upload"><HiddenRecord record={product}/><div className="field"><label htmlFor="photo">Product photo</label><input id="photo" name="photo" type="file" accept="image/jpeg,image/png,image/webp" required/></div><p className="muted-small">JPG, PNG or WebP up to 8 MB. Photos are resized and metadata is removed before storage.</p><button className="button button-primary">Upload photo →</button></ActionForm>}</section><section className="card top-space"><h2>Ready to be discovered?</h2><p>Publishing requires an approved business and at least one photo.</p><ActionForm action="product.status"><HiddenRecord record={product}/><div className="field"><label htmlFor="status">Product status</label><select id="status" name="status" defaultValue={product.status}><option value="draft">Draft — only you and admins</option><option value="published">Published — visible after approval</option><option value="archived">Archived — hidden from customers</option></select></div><button className="button button-primary">Update status →</button></ActionForm>{product.status==="published"&&<p><Link className="text-link" href={`/products/${id}`}>View public product →</Link></p>}</section></div></div></>;}
