"use server";
import { redirect } from "next/navigation";
import { revalidatePath } from "next/cache";
import { requireUser,requireRole } from "@/lib/auth/require-user";
import { isUuid } from "@/lib/businesses";
import { friendlyError,poundsToPence,readText } from "@/lib/marketplace";
export async function requestRefund(form:FormData){const {supabase}=await requireUser();const item=readText(form,"item"),amount=poundsToPence(readText(form,"amount"));if(!isUuid(item)||amount===null)redirect("/orders?error=Invalid%20refund%20request.");const {data,error}=await supabase.rpc("request_refund",{item_id:item,questionnaire:{reason:readText(form,"reason"),explanation:readText(form,"explanation"),requested_pence:amount,contacted_seller:readText(form,"contacted_seller")==="yes",desired_resolution:readText(form,"desired_resolution")}});if(error)redirect(`/refunds/new?item=${item}&error=${encodeURIComponent(friendlyError(error))}`);revalidatePath("/orders","layout");redirect(`/refunds/${data}?message=Your%20request%20has%20been%20sent%20to%20the%20seller.%20You%20can%20add%20evidence%20below.`);}
export async function respondRefund(form:FormData){const {supabase}=await requireUser();const id=readText(form,"id");if(!isUuid(id))redirect("/seller/orders");const {error}=await supabase.rpc("respond_refund",{case_id:id,response_text:readText(form,"response")});revalidatePath(`/refunds/${id}`);redirect(`/refunds/${id}?${error?"error":"message"}=${encodeURIComponent(error?friendlyError(error):"Your response has been submitted for HolyHub review.")}`);}
export async function decideRefund(form:FormData){const {supabase}=await requireRole("admin");const id=readText(form,"id"),amount=poundsToPence(readText(form,"amount"));if(!isUuid(id)||amount===null)redirect("/admin/refunds?error=Invalid%20decision.");const {error}=await supabase.rpc("decide_refund",{case_id:id,decision:readText(form,"decision"),amount_pence:amount,note:readText(form,"note")});revalidatePath("/admin/refunds");revalidatePath(`/refunds/${id}`);redirect(`/refunds/${id}?${error?"error":"message"}=${encodeURIComponent(error?friendlyError(error):"Decision recorded. No money has been sent; payment processing is not connected.")}`);}
export async function appealRefund(form:FormData){const {supabase}=await requireUser();const id=readText(form,"id");if(!isUuid(id))redirect("/orders");const {error}=await supabase.rpc("appeal_refund",{case_id:id,explanation:readText(form,"explanation")});revalidatePath(`/refunds/${id}`);redirect(`/refunds/${id}?${error?"error":"message"}=${encodeURIComponent(error?friendlyError(error):"Your appeal is with HolyHub for review.")}`);}
