import Link from "next/link";
import { ProductGallery } from "@/components/product-gallery";
import { notFound } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { isUuid } from "@/lib/businesses";
import { money,type Product } from "@/lib/marketplace";
import { SubmitButton } from "@/components/submit-button";
import { Notices } from "@/components/notices";
import { updateBasket } from "@/app/basket/actions";
export default async function ProductDetail({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{error?:string;message?:string}>}){
 const {id}=await params;if(!isUuid(id))notFound();const supabase=await createClient();const {data,error}=await supabase.from("products").select("*").eq("id",id).eq("status","published").eq("moderation_status","visible").maybeSingle();if(error)throw new Error("Product unavailable");if(!data)notFound();const p=data as Product;
 const [{data:business,error:businessError},{data:images,error:imagesError}]=await Promise.all([supabase.from("businesses").select("id,name,status").eq("id",p.business_id).maybeSingle(),supabase.from("product_images").select("id").eq("product_id",id).order("created_at") ]);if(businessError||imagesError)throw new Error("Product details unavailable");if(!business||business.status!=="approved")notFound();
 return <><Link className="text-link" href="/products">← All products</Link><Notices {...await searchParams}/><div className="product-detail-grid"><ProductGallery key={id} productId={id} name={p.name} images={images??[]}/><section><p className="eyebrow">{p.category}</p><h1 className="page-title">{p.name}</h1><Link href={`/businesses/${business.id}`} className="text-link">By {business.name}</Link><p className="product-price">{money(p.price_pence)}</p><p className="preserve-lines">{p.description}</p><form action={updateBasket} className="form top-space"><input type="hidden" name="id" value={id}/><input type="hidden" name="intent" value="add"/><div className="field quantity-field"><label htmlFor="quantity">Quantity</label><input id="quantity" name="quantity" type="number" min={1} max={Math.min(p.stock,99)||1} defaultValue={1} required/></div>{p.stock?<SubmitButton pendingText="Adding…">Add to basket →</SubmitButton>:<button className="button button-quiet" disabled>Sold out</button>}</form><p className="muted-small">Sign in to save your basket. Payments are not enabled yet.</p><div className="story"><h2>Delivery & fulfilment</h2><p className="preserve-lines">{p.delivery_info}</p><p className="muted-small">Final shipping and tax treatment must be confirmed before checkout opens.</p></div><a className="text-link" href={`mailto:Official.holyhub@gmail.com?subject=${encodeURIComponent(`Product query: ${p.name} (${id})`)}`}>Report a concern</a></section></div></>;
}
