import { ActionForm } from "./action-form";
import { businessCategories, productCategories, type Business, type Product, type Event } from "@/lib/data";

export function Field({name,label,value="",max=200,required=true,area=false,type="text"}:{name:string;label:string;value?:string|number;max?:number;required?:boolean;area?:boolean;type?:string}) {
  return <div className="field"><label htmlFor={name}>{label}</label>{area?<textarea id={name} name={name} defaultValue={value} maxLength={max} required={required} rows={5}/>:<input id={name} name={name} defaultValue={value} maxLength={max} required={required} type={type}/>}</div>;
}
export function HiddenRecord({record}:{record:{id:string;version:number}}){return <><input type="hidden" name="id" value={record.id}/><input type="hidden" name="version" value={record.version}/></>;}
function Category({values,value}:{values:string[];value?:string}){return <div className="field"><label htmlFor="category">Category</label><select id="category" name="category" defaultValue={value||values[0]}>{values.map(value=><option key={value}>{value}</option>)}</select></div>;}
export function BusinessForm({business}:{business:Business|null}){return <ActionForm action="business.save">{business&&<HiddenRecord record={business}/>}<Field name="name" label="Business or brand name" value={business?.name} max={100}/><div className="form-columns"><Category values={businessCategories} value={business?.category}/><Field name="location" label="Location" value={business?.location} max={120}/></div><Field name="summary" label="Short introduction" value={business?.summary} max={240}/><Field name="description" label="Your story & what you offer" value={business?.description} max={4000} area/><Field name="website" label="Website or social profile (optional)" value={business?.website} max={500} required={false} type="url"/><label className="check-field"><input type="checkbox" name="faith" value="yes" required/><span>I confirm this is my Christian business and I have permission to share its information.</span></label><p className="muted-small">Your profile is reviewed before appearing publicly. Changes to an approved profile return it and its products to review.</p><button className="button button-primary">{business?"Save & submit for review":"Submit for review"} →</button></ActionForm>;}
export function ProductForm({product}:{product:Product|null}){return <ActionForm action="product.save">{product&&<HiddenRecord record={product}/>}<Field name="name" label="Product name" value={product?.name} max={120}/><Category values={productCategories} value={product?.category}/><Field name="description" label="Product description" value={product?.description} max={4000} area/><div className="form-columns"><Field name="price" label="Price (£)" value={product?(product.price_pence/100).toFixed(2):""} max={12}/><Field name="stock" label="Available quantity" value={product?.stock??1} max={6}/></div><Field name="delivery_info" label="Delivery or collection information" value={product?.delivery_info} max={1500} area/><p className="muted-small">Saving returns the product to draft. Add a photo and publish when you’re ready. Customers contact your business directly; HolyHub checkout is not enabled.</p><button className="button button-primary">Save product →</button></ActionForm>;}
export function EventForm({event}:{event:Event|null}){return <ActionForm action="event.save">{event&&<HiddenRecord record={event}/>}<Field name="name" label="Event name" value={event?.name} max={120}/><Field name="organiser" label="Organiser" value={event?.organiser} max={120}/><Field name="location" label="Location or online platform" value={event?.location} max={160}/><Field name="schedule" label="Date, time and timezone / recurring schedule" value={event?.schedule} max={400}/><Field name="description" label="About this event" value={event?.description} max={4000} area/><Field name="website" label="Organiser or booking website" value={event?.website} max={500} type="url"/><p className="muted-small">Saving returns the event to draft. Review all details, then publish.</p><button className="button button-primary">Save event →</button></ActionForm>;}
