import Link from "@/components/site-link";
import { all, one, productSelect, visibleProducts, productCategories, search, like, pageNumber, type Product } from "@/lib/data";
import { ProductCard } from "@/components/product-card";
import { Empty } from "@/components/page-ui";
export const metadata={title:"Discover Christian brands"};
export default async function Products({searchParams}:{searchParams:Promise<{q?:string;category?:string;sort?:string;stock?:string;page?:string}>}) {
 const params=await searchParams,q=search(params.q),category=productCategories.includes(params.category||"")?params.category!:"",page=pageNumber(params.page);
 const args:unknown[]=[];let where=visibleProducts;
 if(q){where+=" AND (p.name LIKE ? ESCAPE '\\' OR p.description LIKE ? ESCAPE '\\' OR b.name LIKE ? ESCAPE '\\')";args.push(like(q),like(q),like(q));}
 if(category){where+=" AND p.category=?";args.push(category);}if(params.stock==="yes")where+=" AND p.stock>0";
 const order=params.sort==="price_low"?"p.price_pence ASC":params.sort==="price_high"?"p.price_pence DESC":"p.created_at DESC";
 const rows=await all<Product>(productSelect+" WHERE "+where+" ORDER BY "+order+",p.id LIMIT 12 OFFSET ?",...args,(page-1)*12);
 const count=(await one<{total:number}>("SELECT count(*) total FROM hh_products p JOIN hh_businesses b ON b.id=p.business_id JOIN hh_members m ON m.id=b.owner_id WHERE "+where,...args))?.total||0;
 const link=(n:number)=>"/products?"+new URLSearchParams({q,category,sort:params.sort||"newest",stock:params.stock||"",page:String(n)});
 return <><div className="section-heading"><p className="eyebrow">Christian brands. Meaningful finds.</p><h1 className="page-title">Good things, waiting to be found.</h1><p className="lead">Independent businesses. Thoughtfully made. Discover products and connect directly with the brands behind them.</p></div><form className="market-filters" action="/products" role="search"><div className="field filter-search"><label htmlFor="q">Search products</label><input id="q" name="q" type="search" defaultValue={q} placeholder="Find your next favourite…" maxLength={80}/></div><div className="field"><label htmlFor="category">Category</label><select id="category" name="category" defaultValue={category}><option value="">All categories</option>{productCategories.map(c=><option key={c}>{c}</option>)}</select></div><div className="field"><label htmlFor="sort">Sort by</label><select id="sort" name="sort" defaultValue={params.sort}><option value="newest">Newest</option><option value="price_low">Price: low to high</option><option value="price_high">Price: high to low</option></select></div><label className="check-field"><input type="checkbox" name="stock" value="yes" defaultChecked={params.stock==="yes"}/><span>In stock only</span></label><button className="button button-primary">Find products →</button></form><div className="results-heading"><p>{count} {count===1?"product":"products"} to discover</p><Link className="text-link" href="/products">Clear filters</Link></div>{rows.length?<div className="product-grid">{rows.map(p=><ProductCard key={p.id} product={p}/>)}</div>:<Empty title={q||category?"No matches just yet.":"The collection starts with you."}><p>{q||category?"Try another search, or explore all categories.":"We’re welcoming our first independent Christian businesses. Bring something worth discovering."}</p><Link className="button button-primary" href={q||category?"/products":"/account/business"}>{q||category?"Explore all products":"Become a Lister"} →</Link></Empty>}{(count>12||page>1)&&<nav className="pagination" aria-label="Product pages">{page>1?<Link className="button button-quiet" href={link(page-1)}>← Previous</Link>:<span/>}<span>Page {page}</span>{page*12<count&&<Link className="button button-quiet" href={link(page+1)}>Next →</Link>}</nav>}<div className="listing-invite"><div><h2>Meet the people behind the products.</h2><p>Explore the Christian businesses making it all happen.</p></div><Link className="button button-quiet" href="/businesses">Meet the brands →</Link></div></>;
}
