import Image from "next/image";
import Link from "next/link";
import { requireUser } from "@/lib/auth/require-user";
import { money,type Product } from "@/lib/marketplace";
import { MarketNav } from "@/components/market-nav";
import { Notices } from "@/components/notices";
import { SubmitButton } from "@/components/submit-button";
import { updateBasket,reviewBasket } from "./actions";
export default async function BasketPage({searchParams}:{searchParams:Promise<{error?:string;message?:string}>}){
 const {supabase,user}=await requireUser("/basket");const {data:items,error}=await supabase.from("basket_items").select("*").eq("user_id",user.id).order("updated_at");if(error)throw new Error("Basket unavailable");const ids=items.map(i=>i.product_id);const {data:products,error:pError}=ids.length?await supabase.from("products").select("*").in("id",ids):{data:[],error:null};if(pError)throw new Error("Basket products unavailable");const map=new Map((products as Product[]).map(p=>[p.id,p]));const availableItem=(item:typeof items[number])=>{const p=map.get(item.product_id);return !!p&&p.status==="published"&&p.moderation_status==="visible"&&p.stock>=item.quantity;};const total=items.reduce((sum,item)=>sum+(availableItem(item)?map.get(item.product_id)!.price_pence*item.quantity:0),0);const unavailable=items.some(item=>!availableItem(item));
 return <><MarketNav/><div className="section-heading"><p className="eyebrow">A few good finds</p><h1 className="page-title">Your basket.</h1><p>Mix products from different Christian brands in one basket.</p></div><Notices {...await searchParams}/>{!items.length?<div className="empty-state card"><h2>Your next favourite is out there.</h2><p>Your basket is empty. Explore the collection to get started.</p><Link className="button button-primary" href="/products">Discover products →</Link></div>:<div className="basket-layout"><div className="record-list">{items.map(item=>{const p=map.get(item.product_id),available=availableItem(item);return <article className="basket-row" key={item.product_id}><Image src={`/api/product-image/${item.product_id}`} alt="" width={90} height={90} unoptimized/><div className="basket-item-copy"><h2>{p?<Link href={`/products/${p.id}`}>{p.name}</Link>:"Product unavailable"}</h2><p>{p?money(p.price_pence):"This product is no longer public."}{!available&&<span className="unavailable"> · Review availability</span>}</p><div className="button-row compact"><form action={updateBasket} className="quantity-form"><input type="hidden" name="id" value={item.product_id}/><label className="sr-only" htmlFor={`qty-${item.product_id}`}>Quantity for {p?.name??"product"}</label><input id={`qty-${item.product_id}`} type="number" min={1} max={99} name="quantity" defaultValue={item.quantity}/><SubmitButton className="button button-quiet" pendingText="Saving…">Update</SubmitButton></form><form action={updateBasket}><input type="hidden" name="id" value={item.product_id}/><input type="hidden" name="quantity" value="0"/><SubmitButton className="button button-quiet">Remove</SubmitButton></form></div></div></article>;})}</div><aside className="card order-summary"><h2>Your order preview</h2><div className="meta-row"><span>Available items</span><strong>{money(total)}</strong></div><p className="muted-small">Shipping and taxes are not calculated yet. Your basket does not reserve stock.</p>{unavailable?<p className="notice notice-error">Update or remove unavailable items before continuing.</p>:<form action={reviewBasket}><SubmitButton pendingText="Checking availability…">Review order →</SubmitButton></form>}<p className="muted-small">This creates an unpaid preview. No charge is made.</p></aside></div>}</>;
}
